development:
  adapter: postgresql
  encoding: unicode
  database: food-order-db
  pool: 5
  username: foodguy
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: food-order-db
  pool: 5
  username: foodguy
  password: password1
